// whatsmeow.proto — driver-neutral surface of the whatsmeow Go service.
//
// 1:1 mirror of the `WaContract` interface declared at
// /home/syntax/work/active/manybot/dev/src/kernel/waContract.ts.
// Every method on the contract maps to an RPC here; any RPC that
// whatsmeow cannot (or does not yet) implement returns codes.Unimplemented
// from the server, and the Node client (`src/drivers/whatsmeow/client.ts`)
// translates that into `NotImplementedError` so plugins fail loud.
//
// Event payloads are the same driver-neutral shapes used by the
// contract (BotMessage, BotQuotedRef, etc.) — adapters translate from
// the raw whatsmeow event shape into these envelopes.
//
// This file is the source of truth. `scripts/generate-proto.sh`
// mirrors it into `src/drivers/whatsmeow/whatsmeow.proto` (Node only
// uses @grpc/proto-loader dynamic loading, no codegen).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: whatsmeow.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WhatsmeowService_Connect_FullMethodName                 = "/whatsmeow.WhatsmeowService/Connect"
	WhatsmeowService_Disconnect_FullMethodName              = "/whatsmeow.WhatsmeowService/Disconnect"
	WhatsmeowService_HealthCheck_FullMethodName             = "/whatsmeow.WhatsmeowService/HealthCheck"
	WhatsmeowService_SubscribeEvents_FullMethodName         = "/whatsmeow.WhatsmeowService/SubscribeEvents"
	WhatsmeowService_VerifySent_FullMethodName              = "/whatsmeow.WhatsmeowService/VerifySent"
	WhatsmeowService_GetHistory_FullMethodName              = "/whatsmeow.WhatsmeowService/GetHistory"
	WhatsmeowService_SendText_FullMethodName                = "/whatsmeow.WhatsmeowService/SendText"
	WhatsmeowService_SendImage_FullMethodName               = "/whatsmeow.WhatsmeowService/SendImage"
	WhatsmeowService_SendVideo_FullMethodName               = "/whatsmeow.WhatsmeowService/SendVideo"
	WhatsmeowService_SendAudio_FullMethodName               = "/whatsmeow.WhatsmeowService/SendAudio"
	WhatsmeowService_SendSticker_FullMethodName             = "/whatsmeow.WhatsmeowService/SendSticker"
	WhatsmeowService_SendDocument_FullMethodName            = "/whatsmeow.WhatsmeowService/SendDocument"
	WhatsmeowService_SendPoll_FullMethodName                = "/whatsmeow.WhatsmeowService/SendPoll"
	WhatsmeowService_React_FullMethodName                   = "/whatsmeow.WhatsmeowService/React"
	WhatsmeowService_DeleteMessage_FullMethodName           = "/whatsmeow.WhatsmeowService/DeleteMessage"
	WhatsmeowService_EditMessage_FullMethodName             = "/whatsmeow.WhatsmeowService/EditMessage"
	WhatsmeowService_SendPresence_FullMethodName            = "/whatsmeow.WhatsmeowService/SendPresence"
	WhatsmeowService_MarkRead_FullMethodName                = "/whatsmeow.WhatsmeowService/MarkRead"
	WhatsmeowService_OnWhatsApp_FullMethodName              = "/whatsmeow.WhatsmeowService/OnWhatsApp"
	WhatsmeowService_GetBusinessProfile_FullMethodName      = "/whatsmeow.WhatsmeowService/GetBusinessProfile"
	WhatsmeowService_ProfilePictureUrl_FullMethodName       = "/whatsmeow.WhatsmeowService/ProfilePictureUrl"
	WhatsmeowService_FetchStatus_FullMethodName             = "/whatsmeow.WhatsmeowService/FetchStatus"
	WhatsmeowService_UpdateBlockStatus_FullMethodName       = "/whatsmeow.WhatsmeowService/UpdateBlockStatus"
	WhatsmeowService_AddOrEditContact_FullMethodName        = "/whatsmeow.WhatsmeowService/AddOrEditContact"
	WhatsmeowService_RemoveContact_FullMethodName           = "/whatsmeow.WhatsmeowService/RemoveContact"
	WhatsmeowService_GetGroupMetadata_FullMethodName        = "/whatsmeow.WhatsmeowService/GetGroupMetadata"
	WhatsmeowService_UpdateGroupParticipants_FullMethodName = "/whatsmeow.WhatsmeowService/UpdateGroupParticipants"
	WhatsmeowService_UpdateGroupSubject_FullMethodName      = "/whatsmeow.WhatsmeowService/UpdateGroupSubject"
	WhatsmeowService_UpdateGroupDescription_FullMethodName  = "/whatsmeow.WhatsmeowService/UpdateGroupDescription"
	WhatsmeowService_GetGroupInviteCode_FullMethodName      = "/whatsmeow.WhatsmeowService/GetGroupInviteCode"
	WhatsmeowService_RevokeGroupInvite_FullMethodName       = "/whatsmeow.WhatsmeowService/RevokeGroupInvite"
	WhatsmeowService_UpdateProfilePicture_FullMethodName    = "/whatsmeow.WhatsmeowService/UpdateProfilePicture"
	WhatsmeowService_UpdateProfileName_FullMethodName       = "/whatsmeow.WhatsmeowService/UpdateProfileName"
	WhatsmeowService_UpdateProfileStatus_FullMethodName     = "/whatsmeow.WhatsmeowService/UpdateProfileStatus"
	WhatsmeowService_Me_FullMethodName                      = "/whatsmeow.WhatsmeowService/Me"
	WhatsmeowService_DownloadMedia_FullMethodName           = "/whatsmeow.WhatsmeowService/DownloadMedia"
)

// WhatsmeowServiceClient is the client API for WhatsmeowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WhatsmeowServiceClient interface {
	// Lifecycle
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error)
	// Events (server-streaming)
	SubscribeEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WaEvent], error)
	// Verification primitives (used by sendFallbackGuard in Node)
	VerifySent(ctx context.Context, in *JidAndId, opts ...grpc.CallOption) (*VerifyResult, error)
	GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error)
	// Send
	SendText(ctx context.Context, in *SendTextRequest, opts ...grpc.CallOption) (*SentMessageRef, error)
	SendImage(ctx context.Context, in *SendMediaRequest, opts ...grpc.CallOption) (*SentMessageRef, error)
	SendVideo(ctx context.Context, in *SendMediaRequest, opts ...grpc.CallOption) (*SentMessageRef, error)
	SendAudio(ctx context.Context, in *SendMediaRequest, opts ...grpc.CallOption) (*SentMessageRef, error)
	SendSticker(ctx context.Context, in *SendMediaRequest, opts ...grpc.CallOption) (*SentMessageRef, error)
	SendDocument(ctx context.Context, in *SendDocumentRequest, opts ...grpc.CallOption) (*SentMessageRef, error)
	SendPoll(ctx context.Context, in *SendPollRequest, opts ...grpc.CallOption) (*SentMessageRef, error)
	// React / edit / delete
	React(ctx context.Context, in *ReactRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*Empty, error)
	EditMessage(ctx context.Context, in *EditMessageRequest, opts ...grpc.CallOption) (*SentMessageRef, error)
	// Presence + read
	SendPresence(ctx context.Context, in *SendPresenceRequest, opts ...grpc.CallOption) (*Empty, error)
	MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*Empty, error)
	// Contacts
	OnWhatsApp(ctx context.Context, in *OnWhatsAppRequest, opts ...grpc.CallOption) (*OnWhatsAppResponse, error)
	GetBusinessProfile(ctx context.Context, in *JidRequest, opts ...grpc.CallOption) (*BusinessProfile, error)
	ProfilePictureUrl(ctx context.Context, in *JidRequest, opts ...grpc.CallOption) (*UrlResponse, error)
	FetchStatus(ctx context.Context, in *JidRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	UpdateBlockStatus(ctx context.Context, in *UpdateBlockStatusRequest, opts ...grpc.CallOption) (*Empty, error)
	AddOrEditContact(ctx context.Context, in *ContactMutationRequest, opts ...grpc.CallOption) (*Empty, error)
	RemoveContact(ctx context.Context, in *JidRequest, opts ...grpc.CallOption) (*Empty, error)
	// Groups
	GetGroupMetadata(ctx context.Context, in *JidRequest, opts ...grpc.CallOption) (*GroupMetadata, error)
	UpdateGroupParticipants(ctx context.Context, in *UpdateGroupParticipantsRequest, opts ...grpc.CallOption) (*UpdateGroupParticipantsResponse, error)
	UpdateGroupSubject(ctx context.Context, in *UpdateGroupTextRequest, opts ...grpc.CallOption) (*Empty, error)
	UpdateGroupDescription(ctx context.Context, in *UpdateGroupTextRequest, opts ...grpc.CallOption) (*Empty, error)
	GetGroupInviteCode(ctx context.Context, in *JidRequest, opts ...grpc.CallOption) (*GroupInviteCodeResponse, error)
	RevokeGroupInvite(ctx context.Context, in *JidRequest, opts ...grpc.CallOption) (*GroupInviteCodeResponse, error)
	// Profile (bot or group)
	UpdateProfilePicture(ctx context.Context, in *UpdateProfilePictureRequest, opts ...grpc.CallOption) (*Empty, error)
	UpdateProfileName(ctx context.Context, in *TextUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
	UpdateProfileStatus(ctx context.Context, in *TextUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
	Me(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MeResponse, error)
	// Media download
	DownloadMedia(ctx context.Context, in *DownloadMediaRequest, opts ...grpc.CallOption) (*MediaBlob, error)
}

type whatsmeowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWhatsmeowServiceClient(cc grpc.ClientConnInterface) WhatsmeowServiceClient {
	return &whatsmeowServiceClient{cc}
}

func (c *whatsmeowServiceClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, WhatsmeowService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, WhatsmeowService_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthStatus)
	err := c.cc.Invoke(ctx, WhatsmeowService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) SubscribeEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WaEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WhatsmeowService_ServiceDesc.Streams[0], WhatsmeowService_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, WaEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WhatsmeowService_SubscribeEventsClient = grpc.ServerStreamingClient[WaEvent]

func (c *whatsmeowServiceClient) VerifySent(ctx context.Context, in *JidAndId, opts ...grpc.CallOption) (*VerifyResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyResult)
	err := c.cc.Invoke(ctx, WhatsmeowService_VerifySent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryResponse)
	err := c.cc.Invoke(ctx, WhatsmeowService_GetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) SendText(ctx context.Context, in *SendTextRequest, opts ...grpc.CallOption) (*SentMessageRef, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SentMessageRef)
	err := c.cc.Invoke(ctx, WhatsmeowService_SendText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) SendImage(ctx context.Context, in *SendMediaRequest, opts ...grpc.CallOption) (*SentMessageRef, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SentMessageRef)
	err := c.cc.Invoke(ctx, WhatsmeowService_SendImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) SendVideo(ctx context.Context, in *SendMediaRequest, opts ...grpc.CallOption) (*SentMessageRef, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SentMessageRef)
	err := c.cc.Invoke(ctx, WhatsmeowService_SendVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) SendAudio(ctx context.Context, in *SendMediaRequest, opts ...grpc.CallOption) (*SentMessageRef, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SentMessageRef)
	err := c.cc.Invoke(ctx, WhatsmeowService_SendAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) SendSticker(ctx context.Context, in *SendMediaRequest, opts ...grpc.CallOption) (*SentMessageRef, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SentMessageRef)
	err := c.cc.Invoke(ctx, WhatsmeowService_SendSticker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) SendDocument(ctx context.Context, in *SendDocumentRequest, opts ...grpc.CallOption) (*SentMessageRef, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SentMessageRef)
	err := c.cc.Invoke(ctx, WhatsmeowService_SendDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) SendPoll(ctx context.Context, in *SendPollRequest, opts ...grpc.CallOption) (*SentMessageRef, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SentMessageRef)
	err := c.cc.Invoke(ctx, WhatsmeowService_SendPoll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) React(ctx context.Context, in *ReactRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, WhatsmeowService_React_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, WhatsmeowService_DeleteMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) EditMessage(ctx context.Context, in *EditMessageRequest, opts ...grpc.CallOption) (*SentMessageRef, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SentMessageRef)
	err := c.cc.Invoke(ctx, WhatsmeowService_EditMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) SendPresence(ctx context.Context, in *SendPresenceRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, WhatsmeowService_SendPresence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, WhatsmeowService_MarkRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) OnWhatsApp(ctx context.Context, in *OnWhatsAppRequest, opts ...grpc.CallOption) (*OnWhatsAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnWhatsAppResponse)
	err := c.cc.Invoke(ctx, WhatsmeowService_OnWhatsApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) GetBusinessProfile(ctx context.Context, in *JidRequest, opts ...grpc.CallOption) (*BusinessProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BusinessProfile)
	err := c.cc.Invoke(ctx, WhatsmeowService_GetBusinessProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) ProfilePictureUrl(ctx context.Context, in *JidRequest, opts ...grpc.CallOption) (*UrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UrlResponse)
	err := c.cc.Invoke(ctx, WhatsmeowService_ProfilePictureUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) FetchStatus(ctx context.Context, in *JidRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, WhatsmeowService_FetchStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) UpdateBlockStatus(ctx context.Context, in *UpdateBlockStatusRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, WhatsmeowService_UpdateBlockStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) AddOrEditContact(ctx context.Context, in *ContactMutationRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, WhatsmeowService_AddOrEditContact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) RemoveContact(ctx context.Context, in *JidRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, WhatsmeowService_RemoveContact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) GetGroupMetadata(ctx context.Context, in *JidRequest, opts ...grpc.CallOption) (*GroupMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupMetadata)
	err := c.cc.Invoke(ctx, WhatsmeowService_GetGroupMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) UpdateGroupParticipants(ctx context.Context, in *UpdateGroupParticipantsRequest, opts ...grpc.CallOption) (*UpdateGroupParticipantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGroupParticipantsResponse)
	err := c.cc.Invoke(ctx, WhatsmeowService_UpdateGroupParticipants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) UpdateGroupSubject(ctx context.Context, in *UpdateGroupTextRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, WhatsmeowService_UpdateGroupSubject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) UpdateGroupDescription(ctx context.Context, in *UpdateGroupTextRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, WhatsmeowService_UpdateGroupDescription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) GetGroupInviteCode(ctx context.Context, in *JidRequest, opts ...grpc.CallOption) (*GroupInviteCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupInviteCodeResponse)
	err := c.cc.Invoke(ctx, WhatsmeowService_GetGroupInviteCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) RevokeGroupInvite(ctx context.Context, in *JidRequest, opts ...grpc.CallOption) (*GroupInviteCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupInviteCodeResponse)
	err := c.cc.Invoke(ctx, WhatsmeowService_RevokeGroupInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) UpdateProfilePicture(ctx context.Context, in *UpdateProfilePictureRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, WhatsmeowService_UpdateProfilePicture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) UpdateProfileName(ctx context.Context, in *TextUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, WhatsmeowService_UpdateProfileName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) UpdateProfileStatus(ctx context.Context, in *TextUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, WhatsmeowService_UpdateProfileStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) Me(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeResponse)
	err := c.cc.Invoke(ctx, WhatsmeowService_Me_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsmeowServiceClient) DownloadMedia(ctx context.Context, in *DownloadMediaRequest, opts ...grpc.CallOption) (*MediaBlob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MediaBlob)
	err := c.cc.Invoke(ctx, WhatsmeowService_DownloadMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WhatsmeowServiceServer is the server API for WhatsmeowService service.
// All implementations must embed UnimplementedWhatsmeowServiceServer
// for forward compatibility.
type WhatsmeowServiceServer interface {
	// Lifecycle
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	Disconnect(context.Context, *Empty) (*Empty, error)
	HealthCheck(context.Context, *Empty) (*HealthStatus, error)
	// Events (server-streaming)
	SubscribeEvents(*Empty, grpc.ServerStreamingServer[WaEvent]) error
	// Verification primitives (used by sendFallbackGuard in Node)
	VerifySent(context.Context, *JidAndId) (*VerifyResult, error)
	GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error)
	// Send
	SendText(context.Context, *SendTextRequest) (*SentMessageRef, error)
	SendImage(context.Context, *SendMediaRequest) (*SentMessageRef, error)
	SendVideo(context.Context, *SendMediaRequest) (*SentMessageRef, error)
	SendAudio(context.Context, *SendMediaRequest) (*SentMessageRef, error)
	SendSticker(context.Context, *SendMediaRequest) (*SentMessageRef, error)
	SendDocument(context.Context, *SendDocumentRequest) (*SentMessageRef, error)
	SendPoll(context.Context, *SendPollRequest) (*SentMessageRef, error)
	// React / edit / delete
	React(context.Context, *ReactRequest) (*Empty, error)
	DeleteMessage(context.Context, *DeleteMessageRequest) (*Empty, error)
	EditMessage(context.Context, *EditMessageRequest) (*SentMessageRef, error)
	// Presence + read
	SendPresence(context.Context, *SendPresenceRequest) (*Empty, error)
	MarkRead(context.Context, *MarkReadRequest) (*Empty, error)
	// Contacts
	OnWhatsApp(context.Context, *OnWhatsAppRequest) (*OnWhatsAppResponse, error)
	GetBusinessProfile(context.Context, *JidRequest) (*BusinessProfile, error)
	ProfilePictureUrl(context.Context, *JidRequest) (*UrlResponse, error)
	FetchStatus(context.Context, *JidRequest) (*StatusResponse, error)
	UpdateBlockStatus(context.Context, *UpdateBlockStatusRequest) (*Empty, error)
	AddOrEditContact(context.Context, *ContactMutationRequest) (*Empty, error)
	RemoveContact(context.Context, *JidRequest) (*Empty, error)
	// Groups
	GetGroupMetadata(context.Context, *JidRequest) (*GroupMetadata, error)
	UpdateGroupParticipants(context.Context, *UpdateGroupParticipantsRequest) (*UpdateGroupParticipantsResponse, error)
	UpdateGroupSubject(context.Context, *UpdateGroupTextRequest) (*Empty, error)
	UpdateGroupDescription(context.Context, *UpdateGroupTextRequest) (*Empty, error)
	GetGroupInviteCode(context.Context, *JidRequest) (*GroupInviteCodeResponse, error)
	RevokeGroupInvite(context.Context, *JidRequest) (*GroupInviteCodeResponse, error)
	// Profile (bot or group)
	UpdateProfilePicture(context.Context, *UpdateProfilePictureRequest) (*Empty, error)
	UpdateProfileName(context.Context, *TextUpdateRequest) (*Empty, error)
	UpdateProfileStatus(context.Context, *TextUpdateRequest) (*Empty, error)
	Me(context.Context, *Empty) (*MeResponse, error)
	// Media download
	DownloadMedia(context.Context, *DownloadMediaRequest) (*MediaBlob, error)
	mustEmbedUnimplementedWhatsmeowServiceServer()
}

// UnimplementedWhatsmeowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWhatsmeowServiceServer struct{}

func (UnimplementedWhatsmeowServiceServer) Connect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedWhatsmeowServiceServer) Disconnect(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedWhatsmeowServiceServer) HealthCheck(context.Context, *Empty) (*HealthStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedWhatsmeowServiceServer) SubscribeEvents(*Empty, grpc.ServerStreamingServer[WaEvent]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedWhatsmeowServiceServer) VerifySent(context.Context, *JidAndId) (*VerifyResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifySent not implemented")
}
func (UnimplementedWhatsmeowServiceServer) GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedWhatsmeowServiceServer) SendText(context.Context, *SendTextRequest) (*SentMessageRef, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendText not implemented")
}
func (UnimplementedWhatsmeowServiceServer) SendImage(context.Context, *SendMediaRequest) (*SentMessageRef, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendImage not implemented")
}
func (UnimplementedWhatsmeowServiceServer) SendVideo(context.Context, *SendMediaRequest) (*SentMessageRef, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendVideo not implemented")
}
func (UnimplementedWhatsmeowServiceServer) SendAudio(context.Context, *SendMediaRequest) (*SentMessageRef, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAudio not implemented")
}
func (UnimplementedWhatsmeowServiceServer) SendSticker(context.Context, *SendMediaRequest) (*SentMessageRef, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSticker not implemented")
}
func (UnimplementedWhatsmeowServiceServer) SendDocument(context.Context, *SendDocumentRequest) (*SentMessageRef, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDocument not implemented")
}
func (UnimplementedWhatsmeowServiceServer) SendPoll(context.Context, *SendPollRequest) (*SentMessageRef, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPoll not implemented")
}
func (UnimplementedWhatsmeowServiceServer) React(context.Context, *ReactRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method React not implemented")
}
func (UnimplementedWhatsmeowServiceServer) DeleteMessage(context.Context, *DeleteMessageRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMessage not implemented")
}
func (UnimplementedWhatsmeowServiceServer) EditMessage(context.Context, *EditMessageRequest) (*SentMessageRef, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditMessage not implemented")
}
func (UnimplementedWhatsmeowServiceServer) SendPresence(context.Context, *SendPresenceRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPresence not implemented")
}
func (UnimplementedWhatsmeowServiceServer) MarkRead(context.Context, *MarkReadRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkRead not implemented")
}
func (UnimplementedWhatsmeowServiceServer) OnWhatsApp(context.Context, *OnWhatsAppRequest) (*OnWhatsAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnWhatsApp not implemented")
}
func (UnimplementedWhatsmeowServiceServer) GetBusinessProfile(context.Context, *JidRequest) (*BusinessProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBusinessProfile not implemented")
}
func (UnimplementedWhatsmeowServiceServer) ProfilePictureUrl(context.Context, *JidRequest) (*UrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProfilePictureUrl not implemented")
}
func (UnimplementedWhatsmeowServiceServer) FetchStatus(context.Context, *JidRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchStatus not implemented")
}
func (UnimplementedWhatsmeowServiceServer) UpdateBlockStatus(context.Context, *UpdateBlockStatusRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBlockStatus not implemented")
}
func (UnimplementedWhatsmeowServiceServer) AddOrEditContact(context.Context, *ContactMutationRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddOrEditContact not implemented")
}
func (UnimplementedWhatsmeowServiceServer) RemoveContact(context.Context, *JidRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveContact not implemented")
}
func (UnimplementedWhatsmeowServiceServer) GetGroupMetadata(context.Context, *JidRequest) (*GroupMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupMetadata not implemented")
}
func (UnimplementedWhatsmeowServiceServer) UpdateGroupParticipants(context.Context, *UpdateGroupParticipantsRequest) (*UpdateGroupParticipantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroupParticipants not implemented")
}
func (UnimplementedWhatsmeowServiceServer) UpdateGroupSubject(context.Context, *UpdateGroupTextRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroupSubject not implemented")
}
func (UnimplementedWhatsmeowServiceServer) UpdateGroupDescription(context.Context, *UpdateGroupTextRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroupDescription not implemented")
}
func (UnimplementedWhatsmeowServiceServer) GetGroupInviteCode(context.Context, *JidRequest) (*GroupInviteCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupInviteCode not implemented")
}
func (UnimplementedWhatsmeowServiceServer) RevokeGroupInvite(context.Context, *JidRequest) (*GroupInviteCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeGroupInvite not implemented")
}
func (UnimplementedWhatsmeowServiceServer) UpdateProfilePicture(context.Context, *UpdateProfilePictureRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfilePicture not implemented")
}
func (UnimplementedWhatsmeowServiceServer) UpdateProfileName(context.Context, *TextUpdateRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfileName not implemented")
}
func (UnimplementedWhatsmeowServiceServer) UpdateProfileStatus(context.Context, *TextUpdateRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfileStatus not implemented")
}
func (UnimplementedWhatsmeowServiceServer) Me(context.Context, *Empty) (*MeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Me not implemented")
}
func (UnimplementedWhatsmeowServiceServer) DownloadMedia(context.Context, *DownloadMediaRequest) (*MediaBlob, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadMedia not implemented")
}
func (UnimplementedWhatsmeowServiceServer) mustEmbedUnimplementedWhatsmeowServiceServer() {}
func (UnimplementedWhatsmeowServiceServer) testEmbeddedByValue()                          {}

// UnsafeWhatsmeowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WhatsmeowServiceServer will
// result in compilation errors.
type UnsafeWhatsmeowServiceServer interface {
	mustEmbedUnimplementedWhatsmeowServiceServer()
}

func RegisterWhatsmeowServiceServer(s grpc.ServiceRegistrar, srv WhatsmeowServiceServer) {
	// If the following call pancis, it indicates UnimplementedWhatsmeowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WhatsmeowService_ServiceDesc, srv)
}

func _WhatsmeowService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).Disconnect(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WhatsmeowServiceServer).SubscribeEvents(m, &grpc.GenericServerStream[Empty, WaEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WhatsmeowService_SubscribeEventsServer = grpc.ServerStreamingServer[WaEvent]

func _WhatsmeowService_VerifySent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JidAndId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).VerifySent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_VerifySent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).VerifySent(ctx, req.(*JidAndId))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).GetHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_SendText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).SendText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_SendText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).SendText(ctx, req.(*SendTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_SendImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).SendImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_SendImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).SendImage(ctx, req.(*SendMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_SendVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).SendVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_SendVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).SendVideo(ctx, req.(*SendMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_SendAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).SendAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_SendAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).SendAudio(ctx, req.(*SendMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_SendSticker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).SendSticker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_SendSticker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).SendSticker(ctx, req.(*SendMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_SendDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).SendDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_SendDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).SendDocument(ctx, req.(*SendDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_SendPoll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).SendPoll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_SendPoll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).SendPoll(ctx, req.(*SendPollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_React_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).React(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_React_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).React(ctx, req.(*ReactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_DeleteMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).DeleteMessage(ctx, req.(*DeleteMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_EditMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).EditMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_EditMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).EditMessage(ctx, req.(*EditMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_SendPresence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPresenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).SendPresence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_SendPresence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).SendPresence(ctx, req.(*SendPresenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_MarkRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).MarkRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_MarkRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).MarkRead(ctx, req.(*MarkReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_OnWhatsApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnWhatsAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).OnWhatsApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_OnWhatsApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).OnWhatsApp(ctx, req.(*OnWhatsAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_GetBusinessProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).GetBusinessProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_GetBusinessProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).GetBusinessProfile(ctx, req.(*JidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_ProfilePictureUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).ProfilePictureUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_ProfilePictureUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).ProfilePictureUrl(ctx, req.(*JidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_FetchStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).FetchStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_FetchStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).FetchStatus(ctx, req.(*JidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_UpdateBlockStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBlockStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).UpdateBlockStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_UpdateBlockStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).UpdateBlockStatus(ctx, req.(*UpdateBlockStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_AddOrEditContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContactMutationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).AddOrEditContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_AddOrEditContact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).AddOrEditContact(ctx, req.(*ContactMutationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_RemoveContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).RemoveContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_RemoveContact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).RemoveContact(ctx, req.(*JidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_GetGroupMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).GetGroupMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_GetGroupMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).GetGroupMetadata(ctx, req.(*JidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_UpdateGroupParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).UpdateGroupParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_UpdateGroupParticipants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).UpdateGroupParticipants(ctx, req.(*UpdateGroupParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_UpdateGroupSubject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).UpdateGroupSubject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_UpdateGroupSubject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).UpdateGroupSubject(ctx, req.(*UpdateGroupTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_UpdateGroupDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).UpdateGroupDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_UpdateGroupDescription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).UpdateGroupDescription(ctx, req.(*UpdateGroupTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_GetGroupInviteCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).GetGroupInviteCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_GetGroupInviteCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).GetGroupInviteCode(ctx, req.(*JidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_RevokeGroupInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).RevokeGroupInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_RevokeGroupInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).RevokeGroupInvite(ctx, req.(*JidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_UpdateProfilePicture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfilePictureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).UpdateProfilePicture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_UpdateProfilePicture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).UpdateProfilePicture(ctx, req.(*UpdateProfilePictureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_UpdateProfileName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).UpdateProfileName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_UpdateProfileName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).UpdateProfileName(ctx, req.(*TextUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_UpdateProfileStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).UpdateProfileStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_UpdateProfileStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).UpdateProfileStatus(ctx, req.(*TextUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_Me_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).Me(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_Me_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).Me(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsmeowService_DownloadMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsmeowServiceServer).DownloadMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsmeowService_DownloadMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsmeowServiceServer).DownloadMedia(ctx, req.(*DownloadMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WhatsmeowService_ServiceDesc is the grpc.ServiceDesc for WhatsmeowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WhatsmeowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "whatsmeow.WhatsmeowService",
	HandlerType: (*WhatsmeowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _WhatsmeowService_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _WhatsmeowService_Disconnect_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _WhatsmeowService_HealthCheck_Handler,
		},
		{
			MethodName: "VerifySent",
			Handler:    _WhatsmeowService_VerifySent_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _WhatsmeowService_GetHistory_Handler,
		},
		{
			MethodName: "SendText",
			Handler:    _WhatsmeowService_SendText_Handler,
		},
		{
			MethodName: "SendImage",
			Handler:    _WhatsmeowService_SendImage_Handler,
		},
		{
			MethodName: "SendVideo",
			Handler:    _WhatsmeowService_SendVideo_Handler,
		},
		{
			MethodName: "SendAudio",
			Handler:    _WhatsmeowService_SendAudio_Handler,
		},
		{
			MethodName: "SendSticker",
			Handler:    _WhatsmeowService_SendSticker_Handler,
		},
		{
			MethodName: "SendDocument",
			Handler:    _WhatsmeowService_SendDocument_Handler,
		},
		{
			MethodName: "SendPoll",
			Handler:    _WhatsmeowService_SendPoll_Handler,
		},
		{
			MethodName: "React",
			Handler:    _WhatsmeowService_React_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _WhatsmeowService_DeleteMessage_Handler,
		},
		{
			MethodName: "EditMessage",
			Handler:    _WhatsmeowService_EditMessage_Handler,
		},
		{
			MethodName: "SendPresence",
			Handler:    _WhatsmeowService_SendPresence_Handler,
		},
		{
			MethodName: "MarkRead",
			Handler:    _WhatsmeowService_MarkRead_Handler,
		},
		{
			MethodName: "OnWhatsApp",
			Handler:    _WhatsmeowService_OnWhatsApp_Handler,
		},
		{
			MethodName: "GetBusinessProfile",
			Handler:    _WhatsmeowService_GetBusinessProfile_Handler,
		},
		{
			MethodName: "ProfilePictureUrl",
			Handler:    _WhatsmeowService_ProfilePictureUrl_Handler,
		},
		{
			MethodName: "FetchStatus",
			Handler:    _WhatsmeowService_FetchStatus_Handler,
		},
		{
			MethodName: "UpdateBlockStatus",
			Handler:    _WhatsmeowService_UpdateBlockStatus_Handler,
		},
		{
			MethodName: "AddOrEditContact",
			Handler:    _WhatsmeowService_AddOrEditContact_Handler,
		},
		{
			MethodName: "RemoveContact",
			Handler:    _WhatsmeowService_RemoveContact_Handler,
		},
		{
			MethodName: "GetGroupMetadata",
			Handler:    _WhatsmeowService_GetGroupMetadata_Handler,
		},
		{
			MethodName: "UpdateGroupParticipants",
			Handler:    _WhatsmeowService_UpdateGroupParticipants_Handler,
		},
		{
			MethodName: "UpdateGroupSubject",
			Handler:    _WhatsmeowService_UpdateGroupSubject_Handler,
		},
		{
			MethodName: "UpdateGroupDescription",
			Handler:    _WhatsmeowService_UpdateGroupDescription_Handler,
		},
		{
			MethodName: "GetGroupInviteCode",
			Handler:    _WhatsmeowService_GetGroupInviteCode_Handler,
		},
		{
			MethodName: "RevokeGroupInvite",
			Handler:    _WhatsmeowService_RevokeGroupInvite_Handler,
		},
		{
			MethodName: "UpdateProfilePicture",
			Handler:    _WhatsmeowService_UpdateProfilePicture_Handler,
		},
		{
			MethodName: "UpdateProfileName",
			Handler:    _WhatsmeowService_UpdateProfileName_Handler,
		},
		{
			MethodName: "UpdateProfileStatus",
			Handler:    _WhatsmeowService_UpdateProfileStatus_Handler,
		},
		{
			MethodName: "Me",
			Handler:    _WhatsmeowService_Me_Handler,
		},
		{
			MethodName: "DownloadMedia",
			Handler:    _WhatsmeowService_DownloadMedia_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeEvents",
			Handler:       _WhatsmeowService_SubscribeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "whatsmeow.proto",
}
